import {StyleSheet} from 'react-native';
import {primary_color, body_color, input_color} from '../styles/color';

export const globalStyles = StyleSheet.create({
  container: {
    padding: 10,
    flex: 1,
    justifyContent: 'center',
    backgroundColor: body_color,
  },
  inputContainer: {
    height: 45,
    width: 350,
    fontSize: 18,
    padding: 5,
    borderBottomColor: primary_color,
    borderBottomWidth: StyleSheet.hairlineWidth,
    backgroundColor: '#fff',
    borderRadius: 10,
  },
  TextInput: {
    paddingHorizontal: 10,
    color: '#696969',
    fontWeight: 'normal',
    fontSize: 20,
  },
  Button: {
    backgroundColor: primary_color,
    borderRadius: 10,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  SubmitButton: {
    width: 100,
    height: 100,
    borderRadius: 100 / 2,
    backgroundColor: primary_color,
    justifyContent: 'center',
    alignItems: 'center',
    left: 120,
    marginTop: 10,
    marginBottom: 10,
  },
  ButtonSmall: {
    borderRadius: 10,
    backgroundColor: primary_color,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 16,
    marginHorizontal: 8,
    height: 40,
    marginTop: 10,
    top: 20,
  },
  ButtonText: {
    // fontSize: 18,
    color: '#fff',
    // fontWeight: 'bold',
  },
  ButtonRow: {
    width: '47%',
    backgroundColor: primary_color,
    borderRadius: 10,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    marginBottom: 10,
  },
  Row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    //alignSelf: 'flex-end',
  },
  Heading: {
    flex: 1,
    width: '60%',
    borderRadius: 10,
    height: 45,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginBottom: 10,
    fontWeight: 'bold',
    color: primary_color,
    fontSize: 18,
  },
  BlockHeading: {
    backgroundColor: primary_color,
    padding: 10,
    color: '#fff',
    fontWeight: 'bold',
    borderRadius: 2,
    marginTop: 50,
    marginBottom: 30,
  },
  NormalFlex: {
    marginTop: 30,
  },
  Card: {
    width: '100%',
    backgroundColor: primary_color,
    borderRadius: 10,
    height: 150,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  CardText: {
    fontSize: 40,
    color: '#fff',
    fontWeight: 'bold',
  },
  DirectionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  nameTxt: {
    marginLeft: 15,
    fontWeight: 'normal',
    color: primary_color,
    fontSize: 20,
    textTransform: 'capitalize',
  },
  mainContent: {
    marginBottom: 3,
    marginTop: 1,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderColor: primary_color,
    backgroundColor: '#fff',
  },
  loader: {
    flex: 1,
  },
  pickerContainer: {
    padding: 10,
    height: 40,
    width: '95%',
    margin: 10,
    backgroundColor: input_color,
    borderRadius: 10,
  },
});
