export const REGISTER_A_PATIENT = 'REGISTER_A_PATIENT';
export const REGISTER_A_PATIENT_SUCCESS = 'REGISTER_A_PATIENT_SUCCESS';
export const REGISTER_A_PATIENT_FAILURE = 'REGISTER_A_PATIENT_FAILURE';

export const REGISTER_A_PATIENT_ENABLE_LOADER =
  'REGISTER_A_PATIENT_ENABLE_LOADER';
export const REGISTER_A_PATIENT_DISABLE_LOADER =
  'REGISTER_A_PATIENT_DISABLE_LOADER';
