export const GET_A_PATIENT = 'GET_A_PATIENT';
export const GET_A_PATIENT_SUCCESS = 'GET_A_PATIENT_SUCCESS';
export const GET_A_PATIENT_FAILURE = 'GET_A_PATIENT_FAILURE';

export const GET_A_PATIENT_ENABLE_LOADER = 'GET_A_PATIENT_ENABLE_LOADER';
export const GET_A_PATIENT_DISABLE_LOADER = 'GET_A_PATIENT_DISABLE_LOADER';
