export const GET_PATIENTS = 'GET_PATIENTS';
export const GET_PATIENTS_SUCCESS = 'GET_PATIENTS_SUCCESS';
export const GET_PATIENTS_FAILURE = 'GET_PATIENTS_FAILURE';

export const GET_PATIENTS_ENABLE_LOADER = 'GET_PATIENTS_ENABLE_LOADER';
export const GET_PATIENTS_DISABLE_LOADER = 'GET_PATIENTS_DISABLE_LOADER';
