export const GET_SPECIALISTS = 'LOG_OUT';
export const GET_SPECIALISTS_SUCCESS = 'LOG_OUT_SUCCESS';
export const GET_SPECIALISTS_FAILURE = 'LOG_OUT_FAILURE';

export const GET_SPECIALISTS_ENABLE_LOADER = 'GET_SPECIALISTS_ENABLE_LOADER';
export const GET_SPECIALISTS_DISABLE_LOADER = 'GET_SPECIALISTS_DISABLE_LOADER';
